import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Gowun_Dodum } from "next/font/google";

// export const gowunDodum = Gowun_Dodum({
//   subsets: ["korean"] as any,
//   weight: "400",
//   variable: "--font-gowunDodum",
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}
